services:
  flask-app:
    build:
      context: ../              
      dockerfile: docker/Dockerfile  
    ports:
      - "8080:8080"             
    volumes:
      - ../src:/app/src         
    environment:
      # Garanta que o nome do banco de dados seja minúsculo ou envolva-o em aspas duplas para preservar a capitalização
      - DATABASE_URL=postgresql://postgres:password@db:5432/db_vitivinicultura
      - FLASK_APP=api.app
      - PYTHONPATH=/app/src     
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: db_vitivinicultura  # Use letras minúsculas ou aspas duplas se for usar maiúsculas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: