# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - app-apivitivinicultura

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: echo "DATABASE_URL=${{ secrets.AZURE_DB_URL }}" >> $GITHUB_ENV

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Run tests
      #   run: |
      #     pytest  # Ajuste conforme sua ferramenta de testes

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" # Exclui o diretório do ambiente virtual

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'app-apivitivinicultura'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_124DF55988FE492DAC3E96E947BA7582 }}
          startup-command: 'gunicorn --bind 0.0.0.0:8000 src.api.app:app' # Ajuste o caminho conforme necessário
